### ISSUE TITLE
Predefine an empty user for the initial calendar loading

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/team-contribution-calendar#1]
IMO the "stutter" of loading the first user doesn't look great. Let's do the following:
- [x] predefine an initial user with no data and the right calendar setting (this will also hide the issue of calendar sizes from the users) -> resolved by #11.
- [x] keep the loading indicator running until the first async user is loaded -> resolved by #14.

**Comment by gomorizsolt** [comment]
See also the comment [**here**](https://github.com/c-hive/team-contribution-calendar/issues/9#issuecomment-482936888)

**Comment by gomorizsolt** [comment]
Unfortunately, a newly created GH user also contains one contribution which refers to the registration date.

![Képernyőfotó 2019-04-14 - 23 24 18](https://user-images.githubusercontent.com/30864202/56099392-84934100-5f0c-11e9-85d3-6bc642a759c6.png)

We ended up "resetting" the values to the default ones in this case(contributions / fill colors).

**Comment by gomorizsolt** [comment]
Resolved by #11 and #14.
