### ISSUE TITLE
Separate distified files

### ISSUE THREAD

**Issue by gomorizsolt** [c-hive/team-contribution-calendar#15]
Besides the JavaScript codes, the current [**distified**](https://raw.githubusercontent.com/c-hive/team-contribution-calendar/master/dist/index.min.js) version contains the imported resources at the top of the files. I'm not sure of the proper way of handling this case, but the idea might be to exclude these files and store them separately - as `browserify` provides roughly the same [**functionality**](https://stackoverflow.com/a/41762757/9599137).

Is anyone familiar with this topic? If so, it'd be great if one could leave some ideas/proposals. Either way, let's try to find the "conventionals" / best practices that are related to this particular case.

**Comment by thisismydesign** [comment]
I don't get this. What is the problem to be solved? Both our code and resources are required, why is 1 import less preferable than 2?

**Comment by gomorizsolt** [comment]
I didn't mention that this'd be the preferable way, just thought we wouldn't like to include the resources in the distified file - sorry if the description isn't so precise. Btw, you're absolutely right that it doesn't really worth separating the resources into individual files as these should also be imported one by one - mostly in the CDN version.

It's rather an investigation topic than an issue that should be solved in any cases - but it seems it's not required, thus the issue is closed.
