### ISSUE TITLE
Improve error handling when fetch fails

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/team-contribution-calendar#24]
When fetch fails there's an exception and the loading spinner is stuck. Instead, it should be handled gracefully and it should not remain in a loading state.

**Comment by gomorizsolt** [comment]
To be a bit more precise, it's only stuck if the exception is occurred during the sync fetching. In this case, I'd stop the whole flow by throwing an error - as the `actualCalendar` won't be updated to the appropriate structure that fit the further calendars.

**Comment by thisismydesign** [comment]
Not being updated is fine in this case of course. So is throwing a meaningful error. But please stop the spinner as well. :)

**Comment by gomorizsolt** [comment]
Resolved by #26.
