### ISSUE TITLE
Use c-hive proxy

### ISSUE THREAD

**Issue by thisismydesign** [c-hive/team-contribution-calendar#25]
Our proxy didn't work with a test heroku deployment for some reason, but it should be the default.

**Comment by gomorizsolt** [comment]
It's ridiculous, but the issue with the proxy-server was caused by an inadvertently added extra space before the comma separator within the `CORSANYWHERE_WHITELIST` environment variables list.

Closed.

**Comment by thisismydesign** [comment]
So is our proxy being used then as default or is it still the other? If so feel free to close again. :)

**Comment by gomorizsolt** [comment]
Yes, our proxy is the default one. It seems that it didn't turn out to be fully resolved in my comment above, sorry. :)
