### ISSUE TITLE
Default CORS proxy server is forbidden

### ISSUE THREAD

**Issue by gomorizsolt** [c-hive/team-contribution-calendar#41]
Our [default](https://github.com/c-hive/team-contribution-calendar/blob/master/src/utils/Proxy/Proxy.js#L1) CORS proxy server is forbidden for some reason.

![Képernyőfotó 2019-07-19 - 21 47 12](https://user-images.githubusercontent.com/30864202/61561417-38a5ea00-aa6f-11e9-8b40-8c344cfe064d.png)

Perhaps GitHub denies the requests specifically from our server as TCC works fine with my self-hosted server.

**Comment by thisismydesign** [comment]
> Perhaps GitHub denies the requests specifically from our server

Wouldn't think so. Isn't it the case that not every origin URL whitelisted?

**Comment by gomorizsolt** [comment]
That might be the case, forgot that we whitelist URLs.

**Comment by thisismydesign** [comment]
Yep

**Comment by thisismydesign** [comment]
Added a warning about running an own proxy server to the readme: https://github.com/c-hive/team-contribution-calendar/commit/9703924aa54b9071b2ebe3624ee85515cb9d2239

Extended the default proxy server with regex whitelist capabilities and configured it to allow more development routes: https://github.com/Rob--W/cors-anywhere/compare/Rob--W:4814647...c-hive:25516a7
