### ISSUE TITLE
Remove temporary `resolutions` field once `svgo` fixes their issue

### ISSUE THREAD

**Issue by gomorizsolt** [c-hive/team-contribution-calendar#55]
See:
- https://github.com/svg/svgo/issues/1174
- https://github.com/c-hive/team-contribution-calendar/blob/25415688871e587bf3c834fa253d1beb2420b1f5/package.json#L71-L73

**Comment by thisismydesign** [comment]
The issue seems to be resolved now https://github.com/svg/svgo/pull/1176

**Comment by thisismydesign** [comment]
There was some discussion and misunderstanding about this in https://github.com/c-hive/team-contribution-calendar/pull/62.

TLDR; requirements:
- specify a non-exact dependency (e.g. `1.3.2` and above)
- compatibility of both npm and yarn if possible

See also: https://stackoverflow.com/questions/15806152/how-do-i-override-nested-npm-dependency-versions

Looks like npm has `npm shrinkwrap` for this, while yarn has `resolutions` and neither of them is compatible with the other manager. Let's just add `svgo` as a direct dependency with the correct version and a comment.

**Comment by thisismydesign** [comment]
It's really weird but I can't seem to find a good description of this. My gut feeling is that the solution I proposed wouldn't work. AFAIU
> if an alternate (but still "satisfying") dependency is already installed "further up the tree" as it were, then the buggy one will mercifully NOT get installed as a sub-submodule.

However, this doesn't limit the case when some dependency would explicitly require a broken sub-dependency. In this, we want to tell the user that this will not work. This is a nice free-time investigation if someone wants to score some SO karma, as none of the mentioned threads explain this properly.

Let's stick with yarn for now. Use `^1.3.2` resolution and add a comment to package.json with this issue as well as a mention to the readme to use yarn.

References:
- https://docs.npmjs.com/cli/install#algorithm
- https://stackoverflow.com/questions/11233133/when-installing-a-package-with-npm-can-you-tell-it-to-use-a-different-version-o

**Comment by gomorizsolt** [comment]
As there's no permanent solution for this issue, should we leave this open?

**Comment by gomorizsolt** [comment]
Also, since there's an update in `package.json`, shouldn't we increment the version to `v0.2.1`?

**Comment by thisismydesign** [comment]
Right, there should be a new patch release for this. Afterward, the issue can be closed. The solution we added is good and permanent, it's that it only supports yarn.

**Comment by gomorizsolt** [comment]
- https://github.com/c-hive/team-contribution-calendar/releases/tag/v0.2.1
- https://www.npmjs.com/package/@c-hive/team-contribution-calendar

Resolved by `v0.2.1`.
