### ISSUE TITLE
Timeframe bugs

### ISSUE THREAD

**Issue by gomorizsolt** [c-hive/team-contribution-calendar#67]
Follow-up of #40.

(1) The "X contributions in the last year" message doesn't respect timeframes(i.e. it always displays the contributions from a full-year perspective).

(2) The timeframe's `to` field isn't accurate, i.e. it goes a few days back compared to the date it's given. E.g. when it's set to `2019-09-02` it goes back to `2019-09-01`:

![2020-04-09 12 03 40](https://user-images.githubusercontent.com/30864202/78883735-2f740780-7a5a-11ea-9ace-c08915662967.gif)

It's something that didn't turn out while working on this feature for some reason. My gut feeling is that the way we're "playing" with the dates causes this inaccuracy. We may switch to `moment` for a more precise date comparison rather than relying on the built-in `Date()` object.

**Comment by thisismydesign** [comment]
Let's call these bugs. Pleas fix them asap.

**Comment by gomorizsolt** [comment]
> (2) The timeframe's to field isn't accurate, i.e. it goes a few days back compared to the date it's given. E.g. when it's set to 2019-09-02 it goes back to 2019-09-01:

It seems there's nothing wrong with the comparison. It's rather an issue with the indices.

**Comment by gomorizsolt** [comment]
Resolved by #70.
