### ISSUE TITLE
Full-width calendar restriction

### ISSUE THREAD

**Issue by gomorizsolt** [c-hive/team-contribution-calendar#9]
Make sure that the first **GH** user's calendar is full-width.

Tasks:
- [ ] establish the same flow as before:
   - fetch /  parse the user's calendar,
   - merge it into the actual calendar,
   - calculate the total contributions,
   - render to the screen,
   - **OR** log the error message to the console when the calendar doesn't meet with the requirement(and also abort the flow).
- [ ] copy-paste the **Constraint** part.

**Comment by thisismydesign** [comment]
See: https://github.com/c-hive/team-contribution-calendar/issues/1

**Comment by gomorizsolt** [comment]
Closed in favor of #1. Apply the same flow as before except the full-width restriction.

As a part of the issue, we may also [**separate**](https://stackoverflow.com/questions/41762055/browserify-get-external-json-data) the "browserifying" process(i.e. not to include the `BasicCalendar` in the minified JS version).
